import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { HydrationOverlay } from '@builder.io/react-hydration-overlay';

import { cn } from '@/utils/cn.util';
import { TanstackProvider } from '@/providers/tanstack-provider';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: WithChildren) {
  return (
    <HydrationOverlay>
      <TanstackProvider>
        <html lang="en" suppressHydrationWarning>
          <body className={cn(inter.className, 'w-full min-h-svh bg-white')}>
            {children}
          </body>
        </html>
      </TanstackProvider>
    </HydrationOverlay>
  );
}
